os:
  - osx
  - linux
env:
  - TEST_SUITE=ios
  - TEST_SUITE=android
  - TEST_SUITE=ios-browser
  - TEST_SUITE=android-browser
  - TEST_SUITE=desktop-browser
matrix:
    fast_finish: true
    exclude:
      - os: osx
        env: TEST_SUITE=ios
      - os: osx
        env: TEST_SUITE=android
      - os: osx
        env: TEST_SUITE=ios-browser
      - os: osx
        env: TEST_SUITE=android-browser
      - os: osx
        env: TEST_SUITE=desktop-browser
      - os: linux
        env: TEST_SUITE=ios
      - os: linux
        env: TEST_SUITE=android
      - os: linux
        env: TEST_SUITE=ios-browser
      - os: linux
        env: TEST_SUITE=android-browser
      - os: linux
        env: TEST_SUITE=desktop-browser
    include:
      - os: osx
        env: TEST_SUITE=ios
        osx_image:
          - xcode9
        language:
          - objective-c
        before_install:
          - brew update
          - brew install carthage > /dev/null 2>&1
          - brew install ios-webkit-debug-proxy > /dev/null 2>&1
          - brew install nvm > /dev/null 2>&1
        before_script:
          - source $(brew --prefix nvm)/nvm.sh
          - nvm install 7
          - npm i ios-simulator -g
          - open -a Simulator --args -CurrentDeviceUDID `ios-simulator -n 'iPhone 6s'` > /dev/null 2>&1
        script:
          - make travis-ios
      - os: osx
        env: TEST_SUITE=ios-browser
        osx_image:
          - xcode9
        language:
          - objective-c
        before_install:
          - brew update
          - brew install carthage > /dev/null 2>&1
          - brew install ios-webkit-debug-proxy > /dev/null 2>&1
          - brew install nvm > /dev/null 2>&1
        before_script:
          - source $(brew --prefix nvm)/nvm.sh
          - nvm install 7
          - npm i ios-simulator -g
          - open -a Simulator --args -CurrentDeviceUDID `ios-simulator -n 'iPhone 6s'` > /dev/null 2>&1
        script:
          - make travis-ios-safari
      - os: linux
        env: TEST_SUITE=android
        jdk: oraclejdk8
        language: android
        android:
          components:
            - tools
            - build-tools-25.0.2
            - platform-tools
            - extra-android-m2repository
            - extra-google-android-support
            - android-25
        sudo: required
        before_install:
          - export CHROME_BIN=chromium-browser
          - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
          - export ANDROID_HOME=/usr/local/android-sdk
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
        before_script:
          - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
          - unzip gradle-3.3-all.zip > /dev/null
          - export GRADLE_HOME=$PWD/gradle-3.3
          - export PATH=$GRADLE_HOME/bin:$PATH
          - . $HOME/.nvm/nvm.sh
          - nvm install 7
          - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
          - emulator -avd test -no-audio -no-window &
          - android-wait-for-emulator
          - adb shell input keyevent 82 &
        script:
          - make travis-android
      - os: linux
        env: TEST_SUITE=android-browser
        jdk: oraclejdk8
        language: android
        android:
          components:
            - tools
            - build-tools-25.0.2
            - platform-tools
            - extra-android-m2repository
            - extra-google-android-support
            - android-25
        sudo: required
        before_install:
          - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
          - unzip gradle-3.3-all.zip > /dev/null
          - export GRADLE_HOME=$PWD/gradle-3.3
          - export PATH=$GRADLE_HOME/bin:$PATH
          - export CHROME_BIN=chromium-browser
          - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
          - export ANDROID_HOME=/usr/local/android-sdk
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
        before_script:
          - . $HOME/.nvm/nvm.sh
          - nvm install 7
          - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
          - emulator -avd test -no-audio -no-window &
          - android-wait-for-emulator
          - adb shell input keyevent 82 &
        script:
          - make travis-android-chrome
      - os: linux
        env: TEST_SUITE=desktop-browser
        language: node_js
        sudo: false
        node_js:
          - 7
        script:
          - make travis-desktop-puppeteer
